[package]
name = "vmdk-rs"
version = "0.1.0"
authors = ["LevelBlue"]
edition = "2021"

[profile.release]
debug = false
lto = true

[lib]
name = "vmdkrs"
path = "src/lib.rs"

[[bin]]
name = "reader"
path = "src/main.rs"

[features]
capi = []

[dependencies]
async-trait = "0.1.89"
byteorder = "1.5"
clap = { version = "4.1.7", features = ["derive"] }
kaitai = { git = "https://github.com/Agile86/kaitai_rust.git", branch = "rust_basic_support_v2" }
regex = "1"
sha-1 = "^0.10"
flate2 = "1"
once_cell = "1.21.3"
thiserror = "2.0.12"

[dev-dependencies]
rand = "0.9"
