[package]
name = "vmdk-rs"
version = "0.1.0"
authors = ["LevelBlue"]
edition = "2024"

[profile.release]
debug = false
lto = true

[lib]
name = "vmdkrs"
path = "src/lib.rs"

[[bin]]
name = "vmdkverify"
path = "src/main.rs"

[features]
capi = []

[dependencies]
async-trait = "0.1.89"
byteorder = "1.5"
clap = { version = "4.1.7", features = ["derive"] }
foyer = { version = "0.22", features = [ "serde" ] }
foyer-common = "0.22"
flate2 = "1"
futures = "0.3.31"
regex = "1"
rust-s3 = "0.37.1"
sha-1 = "^0.10"
tempfile = "3.23.0"
thiserror = "2.0.12"
tokio = { version = "1.47.1", features = ["fs", "io-util", "rt-multi-thread"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "json"] }
url = "2.5.7"

[dev-dependencies]
rand = "0.10"
